### ISSUE TITLE
wrong scale: Gb

### ISSUE THREAD

**Issue by musikai** [lallulli/songpress#32]
Hi,

As I looked into your source code I saw your scale definition of Gb:
`'Gb': (6, ['Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb', 'Fb']), # E#?`
The Gb scale has these notes:
`'Gb': (6, ['Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb', 'F']),`

I know it's a very seldom scale. Thank you for giving us the source code!!!
Kai

**Comment by lallulli** [comment]
Fixed. Thank you!
