### ISSUE TITLE
Error on opening SongPress

### ISSUE THREAD

**Issue by MusicalBob** [lallulli/songpress#35]
I get this error window whenever I start SongPress. Any way to resolve it? (Windows 10 Pro)
![songpress error](https://user-images.githubusercontent.com/41168665/42655964-adfceff0-85eb-11e8-8b93-bfa7b40f97a9.jpg)

Thanks!

**Comment by dleigh** [comment]
I get the same thing (Windows 10 and version 1.6) and the png file is in the img directory so I don't really understand the problem.  Songpress used to not have this problem - don't remember when it started.

**Comment by lallulli** [comment]
I don't think this issue is still relevant with the new version of Songpress, thus I'm closing it. Please reopen the issue if you still get the error message in Songpress 1.7.2.
