### ISSUE TITLE
Fix "Paste Chords" + Custom section formatting + Embed selected text when inserting title/chords etc.

### ISSUE THREAD

**Issue by RyterX** [lallulli/songpress#40]
- Praticamente il tasto "incolla Accordi" non funziona se ci si posiziona alla fine del rigo, quindi se non è succeduto da un qualsiasi carattere (che non sia lo spazio)

- Sarebbe possibile aggiungere la formattazione (font, grassetto-corsivo, ecc..) per singola sezione?
- Quando viene selezionato un blocco di testo e si usa il tasto "ritornello" o "accordi" esso viene cancellato e sostituito dalle parentesi graffe ecc. Sarebbe più utile e funzionale integrare il blocco di testo selezionato all'interno della funzione scelta: quindi se seleziono del testo, e poi premo il tasto "inserisci ritornello", il testo selezionato dovrebbe venire "inglobato" nelle parentesi del ritornello

**Comment by lallulli** [comment]
Point 2 proposes per-section custom formatting.

Look [here](https://www.chordpro.org/chordpro/directives-props_text_legacy/) for a standard way to implement this point.
