### ISSUE TITLE
German chord notation

### ISSUE THREAD

**Issue by lallulli** [lallulli/songpress#42]
From [googlegroups](https://groups.google.com/forum/#!msg/songpress/iO65f-xn8cY/qGkQVIKtAQAJ):

> In fact there are two variants of German notation:
> 1.) if accidentals are used, then it should be Bb, not B
> ... Ab/G#, A, Bb/A#, H, C ...
> That's how chords in "German" note spelling are displayed in Musescore and my preferred style whenever it is available. It's unambiguous and cannot be confused. Finale, the ChordPro reference implementation and maybe others call it "Scandinavian"
> 2.) if you use B and H that's traditional German style
> In that case the chords are
> C, Cis/Des, D, Dis/Es, E, F, Fis/Ges, G, Gis/As, A, Ais/B, H, C
> Still used in classical or traditional music.
> Musescore calls that note spelling "Full German", Finale, the ChordPro reference implementation and maybe others call it "German"

**Comment by lallulli** [comment]
@Axel-Erfurt can you confirm this? Shall I use Bb instead of B in "modern" German notation? Thanks!

**Comment by AnniePerson** [comment]
"modern" German / Scandinavian chord notation is 
C C#/Db D D#/Eb E F F#/Gb G G#/Ab A A#/Bb H C
Minor chords in lower case letters is more common in traditional German notation. In "modern" German / Scandinavian I would prefer upper case e.g. Am Bbm Hm Cm ...

**Comment by lallulli** [comment]
Thank you for your clarification. Fixed in master. If there is any problem, please let me know!
