### ISSUE TITLE
Trying to report an error.

### ISSUE THREAD

**Issue by papajoetucker** [lallulli/songpress#43]
Each time I start the Songpress application (1.7.2) I am getting an error message. 

![image](https://user-images.githubusercontent.com/55421446/65007010-67530c00-d8ca-11e9-980b-cc992d32f62d.png)

Don't know anything about programming.  I couldn't find any other way of reporting this to you.   When I click OK on the Error Message it continues to load and starts the program just fine.  The only thing it does that I don't like is that start the app in minimized form.  Okay.  That's it.  Hope this gets to the right place and the right people.   Joe Tucker

**Comment by lallulli** [comment]
Hi Joe, could you please test the new version 1.8.0, and see if your issue has gone away?

**Comment by papajoetucker** [comment]
Yes sir. Thank you for the update. The issue was fixed.

**Comment by lallulli** [comment]
I'm glad it was fixed, thank you for your feedback!
