### ISSUE TITLE
Suggestion for view

### ISSUE THREAD

**Issue by Shumatic** [lallulli/songpress#45]
Hi
Very good and easy program.
Would it be possible to add a menu for changing colours of TXT chords, backgroun etc. in ,preview?

**Comment by lallulli** [comment]
Hi, thank you. This is definitely on the to-do list. I'm merging a (very old) feature request with a suggested syntax for defining format with this one.

**Comment by AnniePerson** [comment]
You might think about supporting Pango syntax like the upcoming next version of the ChordPro reference implementation.
See https://groups.google.com/forum/#!topic/chordpro/8CsSQn9aJYc

**Comment by lallulli** [comment]
Essentially, you are proposing to implement the directives defined [here](https://www.chordpro.org/chordpro/ChordPro-Directives.html) and possibly extended in the [Pango branch](https://github.com/ChordPro/chordpro/blob/pango/README.PANGO). This may be done (esp. the former).

With respect to the way Songpress works, I miss a directive to define a specific format for chorus.

**Comment by lallulli** [comment]
I've implemented a first, basic version of song formatting which implements standard chordpro [formatting directives](https://www.chordpro.org/chordpro/directives-props_text_legacy/): size, color and font face for text and chords
