### ISSUE TITLE
Moving the very first chord of a line

### ISSUE THREAD

**Issue by AnniePerson** [lallulli/songpress#46]
Moving chords is a Songpress feature that I frequently use: select a chord with Alt+LeftArrow or Alt+RightArrow and move the chord with Shift+Alt+LeftArrow or Shift+Alt+RightArrow.
There's an issue:
Shift+Alt+RightArrow does not move the chord to the right in case the chord is at the start of the line, to be precise: if the opening [ of the chord is the very first character of the line.
I tested with SongPress 1.7.2 on Win10 1903, but the issue is not new.

**Comment by lallulli** [comment]
I'm trying to reproduce the issue, but apparently I can't. IIRC when you first opened the issue, I was able to reproduce it.

Could you please attach a chordpro sample where you cannot move the first chord of a line?

**Comment by AnniePerson** [comment]
In fact I also cannot reproduce the issue by editing a new example. I still have SongPress 1.7.2, just the Windows version changed from 1903 to 2004 but I don't expect that this has any effect.
In case I come across the issue agan I'll post the affected file immediately.

**Comment by lallulli** [comment]
I'm closing the issue. If you run into the problem again, feel free to reopen it. Thanks.
