### ISSUE TITLE
crash on open file

### ISSUE THREAD

**Issue by Axel-Erfurt** [lallulli/songpress#51]
Unfortunately, it is unusable in Linux Mint 20.
When opening a file, the same error message always appears, then the program crashes.

`#---- Notes ----#
Please provide additional information about the crash here

#---- System Information ----#
Songpress Version: 1.7.2
Operating System: Linux 5.4.0-58-generic x86_64
Python Version: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
wxPython Version: 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
wxPython Info: (__WXGTK__, wxGTK, unicode, unicode-wchar, gtk3, wx-assertions-on, phoenix, wxWidgets 3.1.5, autoidman, sip-4.19.24, build-type: development)
Python Encoding: Default=utf-8  File=utf-8
System Architecture: 64bit x86_64
Byte order: little
Frozen: False
#---- End System Information ----#

#---- Traceback Info ----#
*** Tue Dec 15 15:55:03 2020 ***
Traceback (most recent call last):
  File "/tmp/songpress-1.7.2/src/Editor.py", line 291, in OnStyleNeeded
    self.StartStyling(start, 0x1f)
TypeError: StyledTextCtrl.StartStyling(): too many arguments

#---- End Traceback Info ----#`

**Comment by Axel-Erfurt** [comment]
I got it working by changing line 291 in Editor.py from

```python
self.StartStyling(start, 0x1f)`
```

to

```python
self.StartStyling(start)
```

**Comment by Axel-Erfurt** [comment]
I've created german translation files, you can find it  [here](https://www.dropbox.com/s/qkpfzyteu7c80vp/songpress_de.zip?dl=1)

and changed in Globals.py

```python
    languages = {
        'en': "English",
        'it': "Italiano",
        'fr': u"Français",
        'es': u"Español",
        'de': u"German",
    }

    translators = {
        'en': "Luca Allulli",
        'it': "Luca Allulli",
        'fr': "Raoul Schmitt",
        'es': "Miguel Dell'Uomini",
        'de': "Axel Schneider",
    }
```

**Comment by AnniePerson** [comment]
Thanks for providing the German translation.  I'm using a precompiled V1.7.2 from https://github.com/lallulli/songpress/releases/ so I cannot use it yet. Could you please publish an updated version where German can be selected in Tools - Options. Thank you in advance.

**Comment by lallulli** [comment]
Thank you so much @Axel-Erfurt for the German translation! I'll merge it as soon as possible

**Comment by Axel-Erfurt** [comment]
It is also in my [fork](https://github.com/Axel-Erfurt/hypnotix)

**Comment by lallulli** [comment]
I've merged your [real](https://github.com/Axel-Erfurt/songpress) fork. Thank you so much!
