### ISSUE TITLE
Does not run

### ISSUE THREAD

**Issue by JPersson77** [lallulli/songpress#56]
Hi there, the portable version crash upon execution (not tried installing it). Please see the error log below

Thanks for looking into.

Best regards
Jörgen

#---- Notes ----#
Please provide additional information about the crash here

#---- System Information ----#
Songpress Version: 1.8.0
Operating System: Windows 10 (build 19043), 64-bit edition
Python Version: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)]
wxPython Version: 4.1.1 msw (phoenix) wxWidgets 3.1.5
wxPython Info: (__WXMSW__, wxMSW, unicode, unicode-wchar, wx-assertions-on, phoenix, wxWidgets 3.1.5, autoidman, sip-4.19.24, build-type: release)
Python Encoding: Default=utf-8  File=utf-8
System Architecture: 32bit AMD64
Byte order: little
Frozen: True
#---- End System Information ----#

#---- Traceback Info ----#
*** Fri Jul 30 11:02:54 2021 ***
Traceback (most recent call last):
  File "main.py", line 32, in OnInit
  File "C:\Users\Luca Allulli\Documenti\dev\songpress\master\src\SongpressFrame.py", line 266, in __init__
  File "C:\Users\Luca Allulli\Documenti\dev\songpress\master\src\SongpressFrame.py", line 405, in AddTool
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

#---- End Traceback Info ----#

**Comment by JPersson77** [comment]
Tried installing but the issue persists unfortunately

**Comment by AnniePerson** [comment]
I also gave it a try.
I can open Songpress and use it as usual. Editing a file and saving the results worked. 
When closing Songpress an error was displayed, different to the one that JPersson77 reported:

#---- Notes ----#
Please provide additional information about the crash here


#---- System Information ----#
Songpress Version: 1.8.0
Operating System: Windows 10 (Erzeugungsversion 19043), 64-bit Edition
Python Version: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)]
wxPython Version: 4.1.1 msw (phoenix) wxWidgets 3.1.5
wxPython Info: (__WXMSW__, wxMSW, unicode, unicode-wchar, wx-assertions-on, phoenix, wxWidgets 3.1.5, autoidman, sip-4.19.24, build-type: release)
Python Encoding: Default=utf-8  File=utf-8
System Architecture: 32bit AMD64
Byte order: little
Frozen: True
#---- End System Information ----#

#---- Traceback Info ----#
*** Sat Jul 31 22:14:28 2021 ***
Traceback (most recent call last):
  File "C:\Users\Luca Allulli\Documenti\dev\songpress\master\src\SDIMainFrame.py", line 208, in OnClose
  File "C:\Users\Luca Allulli\Documenti\dev\songpress\master\src\SongpressFrame.py", line 432, in SavePreferences
  File "C:\Users\Luca Allulli\Documenti\dev\songpress\master\src\Preferences.py", line 197, in Save
AttributeError: 'Preferences' object has no attribute 'defaultNotation'

#---- End Traceback Info ----#

**Comment by lallulli** [comment]
Unfortunately the way of handling internationalization, that used to work well with previous versions of wxPython, now causes problems in some cases. We need to overhaul the whole mechanism. 

Duplicates #55

**Comment by lallulli** [comment]
@JPersson77 Hi Jörgen,

I've modified the way internationalization works. Hopefully your issue has been resolved, but I cannot verify because the issue did not appear on my PC.

I've uploaded the new [candidate version](https://github.com/lallulli/songpress/releases/tag/1.8.1_RC1). Could you please test it, and let me know if it works now?

Thank you,
Luca

**Comment by lallulli** [comment]
@AnniePerson your problem is a different one: it has been tracked in #54 and also solved in [Songpress 1.8.1](https://github.com/lallulli/songpress/releases/tag/1.8.1_RC1) release candidate. Please give it a try!

**Comment by AnniePerson** [comment]
fixed, thank you

**Comment by JPersson77** [comment]
Hi Luca, I tried the RC1 and am happy to feedback that it works.

Thanks a lot!

**Comment by lallulli** [comment]
Thank you for your feedback! I'm going to officially release the new version in a short time.
